#!/usr/bin/env python3
"""
orchestrator.py — Daily Workflow Optimization Tool
Picks the next pending task from tasks.yaml, calls codex_runner.sh,
saves the result, updates the log, and regenerates README.md.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_DIR = Path(__file__).parent.resolve()


def load_yaml(path: Path):
    with open(path) as f:
        return yaml.safe_load(f)


def save_yaml(path: Path, data):
    with open(path, "w") as f:
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False, sort_keys=False)


def log(msg: str):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def append_run_log(logs_dir: Path, entry: dict):
    logs_dir.mkdir(parents=True, exist_ok=True)
    log_file = logs_dir / "run.log"
    with open(log_file, "a") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def detect_output_extension(content: str) -> str:
    """Guess file extension from the generated content."""
    stripped = content.lstrip()
    if stripped.startswith("#!/usr/bin/env python") or stripped.startswith("#!/usr/bin/python"):
        return ".py"
    if stripped.startswith("#!/usr/bin/env bash") or stripped.startswith("#!/bin/bash") or stripped.startswith("#!/bin/sh"):
        return ".sh"
    # default
    return ".sh"


def regenerate_readme(repo_dir: Path, logs_dir: Path, tools_dir: Path, max_entries: int):
    log_file = logs_dir / "run.log"
    entries = []
    if log_file.exists():
        with open(log_file) as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        entries.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass

    entries_sorted = sorted(entries, key=lambda e: e.get("timestamp", ""), reverse=True)
    recent = entries_sorted[:max_entries]

    rows = []
    for e in recent:
        date = e.get("timestamp", "")[:10]
        slug = e.get("slug", "unknown")
        status = e.get("status", "unknown")
        tool_dir = e.get("tool_dir", "")
        prompt_summary = e.get("prompt_summary", "")
        duration = e.get("duration_seconds", 0)
        rel_dir = Path(tool_dir).name if tool_dir else ""
        link = f"[{slug}](tools/{rel_dir}/)" if rel_dir else slug
        status_icon = "✅" if status == "done" else "❌"
        rows.append(f"| {date} | {link} | {status_icon} {status} | {duration:.0f}s | {prompt_summary} |")

    table = "\n".join(rows) if rows else "_No tools generated yet._"

    pending_count = sum(1 for e in entries if e.get("status") == "pending")
    done_count = sum(1 for e in entries if e.get("status") == "done")
    failed_count = sum(1 for e in entries if e.get("status") == "failed")

    readme = f"""# Daily Workflow Optimization Tool

> Every night, [Codex CLI](https://github.com/openai/codex) autonomously writes a small workflow utility tool based on a task queue.

## How It Works

1. A cron job runs `run_nightly.sh` at 02:00 each night
2. `orchestrator.py` picks the next `pending` task from `tasks.yaml`
3. It calls `codex_runner.sh` with the task prompt
4. The generated tool is saved to `tools/<timestamp>_<slug>/`
5. The log and this README are updated automatically

## Adding New Tasks

Edit `tasks.yaml` and append a new entry:

```yaml
  - id: "006"
    status: "pending"
    slug: "my-new-tool"
    prompt: |
      Write a bash script that does X, Y, and Z.
      Output only the script, no explanation.
```

## Quick Start

```bash
# Install dependencies
pip install pyyaml

# Copy and fill in your API key
cp .env.example .env
$EDITOR .env

# Install the nightly cron job
bash scripts/install.sh

# Run manually (for testing)
python3 orchestrator.py

# Dry run (no files written, no codex called)
python3 orchestrator.py --dry-run
```

## Stats

| Metric | Count |
|--------|-------|
| Done | {done_count} |
| Failed | {failed_count} |
| Pending (in queue) | {pending_count} |

## Generated Tools (most recent first)

| Date | Tool | Status | Duration | Description |
|------|------|--------|----------|-------------|
{table}

---

_README auto-generated by `orchestrator.py`. Last updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}_
"""

    readme_path = repo_dir / "README.md"
    with open(readme_path, "w") as f:
        f.write(readme)
    log(f"README.md updated ({len(recent)} entries)")


def run_task(task: dict, config: dict, dry_run: bool) -> dict:
    slug = task.get("slug", "unknown")
    prompt = task.get("prompt", "").strip()
    task_id = task.get("id", "?")

    codex_cmd = config["codex"]["command"]
    model = config["codex"]["model"]
    timeout = config["codex"]["timeout_seconds"]
    tools_dir = REPO_DIR / config["paths"]["tools_dir"]
    logs_dir = REPO_DIR / config["paths"]["logs_dir"]

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    tool_dir = tools_dir / f"{timestamp}_{slug}"

    prompt_summary = (prompt[:80] + "…") if len(prompt) > 80 else prompt
    prompt_summary = prompt_summary.replace("\n", " ")

    log(f"Task [{task_id}] {slug}: starting")

    if dry_run:
        log(f"DRY RUN — would create: {tool_dir}")
        log(f"DRY RUN — would call: {codex_cmd} --model {model}")
        log(f"DRY RUN — prompt preview: {prompt_summary}")
        return {
            "task_id": task_id,
            "slug": slug,
            "status": "dry_run",
            "tool_dir": str(tool_dir),
            "timestamp": datetime.now().isoformat(),
            "duration_seconds": 0,
            "prompt_summary": prompt_summary,
        }

    tool_dir.mkdir(parents=True, exist_ok=True)
    prompt_file = tool_dir / "prompt.txt"
    prompt_file.write_text(prompt)

    runner = REPO_DIR / "codex_runner.sh"
    cmd = ["bash", str(runner), model, str(prompt_file)]

    start = time.monotonic()
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    duration = time.monotonic() - start

    output = result.stdout.strip()
    stderr = result.stderr.strip()

    if result.returncode != 0 or not output:
        log(f"Task [{task_id}] FAILED (exit {result.returncode}, {duration:.1f}s)")
        if stderr:
            log(f"  stderr: {stderr[:300]}")
        status = "failed"
        output_file = None
    else:
        ext = detect_output_extension(output)
        output_file = tool_dir / f"output{ext}"
        output_file.write_text(output)
        if ext == ".sh":
            output_file.chmod(0o755)
        status = "done"
        log(f"Task [{task_id}] done → {output_file} ({duration:.1f}s)")

    meta = {
        "task_id": task_id,
        "slug": slug,
        "model": model,
        "timestamp": datetime.now().isoformat(),
        "duration_seconds": round(duration, 2),
        "exit_code": result.returncode,
        "status": status,
        "output_file": str(output_file) if output_file else None,
    }
    (tool_dir / "meta.json").write_text(json.dumps(meta, indent=2))

    if stderr:
        (tool_dir / "stderr.txt").write_text(stderr)

    return {
        **meta,
        "tool_dir": str(tool_dir),
        "prompt_summary": prompt_summary,
    }


def main():
    parser = argparse.ArgumentParser(description="Daily workflow optimization orchestrator")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen without running codex or writing files")
    parser.add_argument("--task-id", help="Force-run a specific task ID (even if not pending)")
    args = parser.parse_args()

    config_path = REPO_DIR / "config.yaml"
    if not config_path.exists():
        print("ERROR: config.yaml not found", file=sys.stderr)
        sys.exit(1)

    config = load_yaml(config_path)
    tasks_path = REPO_DIR / config["paths"]["tasks_file"]
    logs_dir = REPO_DIR / config["paths"]["logs_dir"]

    tasks_data = load_yaml(tasks_path)
    tasks = tasks_data.get("tasks", [])

    # Find next task
    if args.task_id:
        task = next((t for t in tasks if str(t.get("id")) == args.task_id), None)
        if not task:
            log(f"ERROR: task id '{args.task_id}' not found")
            sys.exit(1)
    else:
        task = next((t for t in tasks if t.get("status") == "pending"), None)

    if not task:
        log("No pending tasks found. Add more to tasks.yaml.")
        sys.exit(0)

    # Mark in_progress
    if not args.dry_run:
        task["status"] = "in_progress"
        save_yaml(tasks_path, tasks_data)

    try:
        result = run_task(task, config, dry_run=args.dry_run)
    except subprocess.TimeoutExpired:
        log(f"Task [{task.get('id')}] TIMED OUT after {config['codex']['timeout_seconds']}s")
        result = {
            "task_id": task.get("id"),
            "slug": task.get("slug"),
            "status": "failed",
            "tool_dir": "",
            "timestamp": datetime.now().isoformat(),
            "duration_seconds": config["codex"]["timeout_seconds"],
            "prompt_summary": "",
        }
    except Exception as e:
        log(f"Task [{task.get('id')}] ERROR: {e}")
        result = {
            "task_id": task.get("id"),
            "slug": task.get("slug"),
            "status": "failed",
            "tool_dir": "",
            "timestamp": datetime.now().isoformat(),
            "duration_seconds": 0,
            "prompt_summary": "",
        }

    if not args.dry_run:
        # Update task status in tasks.yaml
        task["status"] = result["status"]
        save_yaml(tasks_path, tasks_data)

        # Append to run log
        append_run_log(logs_dir, result)

        # Regenerate README
        if config.get("readme", {}).get("auto_update", True):
            max_entries = config.get("readme", {}).get("max_recent_tools", 20)
            tools_dir = REPO_DIR / config["paths"]["tools_dir"]
            regenerate_readme(REPO_DIR, logs_dir, tools_dir, max_entries)

    final_status = result.get("status", "unknown")
    log(f"Orchestrator finished. Status: {final_status}")
    sys.exit(0 if final_status in ("done", "dry_run") else 1)


if __name__ == "__main__":
    main()
